name: 'Master branch CI'

on:
  pull_request:
    branches:
      - master
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml
